### PR TITLE
Entity Service, SPEAK Setup, Nuget Package Restore

### PR DESCRIPTION
**Pull request by komainu85**

### CODE REVIEW

**Comment by TwentyGotoTen** [comment]
Upstream currently contains your updates as of yesterday along with all other changes made since you forked. Rebase to current upstream and merge in your changes Remember to omit Automapper and Structure map.

**Comment by komainu85** [comment]
How about a refractor to use sitecore to resolve dependencies rather the SM?

**Comment by TwentyGotoTen** [comment]
Yep Discussed exactly that with @ianjohngraham today. Let's do it together tomorrow morning

**Comment by TwentyGotoTen** [comment]
Did you want me to do manual merge?

**Comment by komainu85** [comment]
Yeah think its easier. Did you do it, or want me to delete fork and do the merge?

**Pull request closed without merging**
